- name: Doxygen Action
  # You may pin to the exact commit or the version.
  # uses: mattnotmitt/doxygen-action@e13253538ce85a582a7b09338d541740c0f8d923
  uses: actions/checkout@v3
  with:
    # Path to Doxyfile
    doxyfile-path: ./docs
    # Working directory
    working-directory: ./html/html
    # Generate latex documentation
    enable-latex: false
    # Extra alpine packages for the build environment
    additional-packages: # optional, default is 
